"""
Structured event -> event description text, exactly as the detector was trained.

This is a self-contained copy of dataset_study/textrep.py describe() plus the value
normalisation of dataset_study/loaders.py, so the web app does not import the study
code. The field order and prefixes per source come from event_schema.json, which is
generated by dataset_study/export_samples.py; that script also checks that this module
produces byte-identical text to the training pipeline on every exported sample.
"""

import json
import math
import os
import re

MAX_FIELDS = 20
BOOL_MAP = {"true": 1.0, "false": 0.0, "t": 1.0, "f": 0.0}
PLACEHOLDERS = {"", "-", "nan", "none", "null", "na"}
HOST_RE = re.compile(r"[a-zA-Z]+://[^/\s]+")

with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "event_schema.json"), encoding="utf-8") as _f:
    SCHEMA = json.load(_f)


def humanize(col):
    c = re.sub(r"[._/]+", " ", col).replace("Scr", "source").replace("Des", "destination")
    c = re.sub(r"\bsrc\b", "source", c)
    c = re.sub(r"\bdst\b", "destination", c)
    return re.sub(r"\s+", " ", c).strip().lower()


def fmt(v):
    if abs(v) >= 1e4 or (0 < abs(v) < 1e-3):
        return f"{v:.3g}"
    return f"{v:.4g}"


def _num(v):
    if v is None:
        return float("nan")
    if isinstance(v, bool):
        return float(v)
    if isinstance(v, (int, float)):
        return float(v) if math.isfinite(float(v)) else float("nan")
    s = str(v).strip().lower()
    if s in BOOL_MAP:
        return BOOL_MAP[s]
    try:
        x = float(s)
        return x if math.isfinite(x) else float("nan")
    except ValueError:
        return float("nan")


def _cat(v):
    if v is None:
        return "na"
    s = str(v).strip().lower()
    try:
        s = f"{float(s):g}"
    except ValueError:
        pass
    return "na" if s in PLACEHOLDERS else s


def describe_event(source, fields, http_request=None):
    """Returns (text, unknown_field_names). Missing fields count as absent/zero."""
    if source not in SCHEMA:
        raise ValueError(f"unknown source {source!r}; expected one of {sorted(SCHEMA)}")
    spec = SCHEMA[source]
    fields = fields or {}
    known = set(spec["categorical"]) | set(spec["numeric"])
    unknown = sorted(k for k in fields if k not in known)
    parts = []
    if http_request and spec.get("has_http"):
        h = HOST_RE.sub("", str(http_request)).strip()
        if h:
            parts.append(f"http request {h}")
    for c in spec["categorical"]:
        v = _cat(fields.get(c))
        if v not in ("na", "0", ""):
            parts.append(f"{humanize(c)} {v}")
    for c in spec["numeric"]:
        v = _num(fields.get(c))
        if not math.isnan(v) and v != 0:
            parts.append(f"{humanize(c)} {fmt(v)}")
    body = ", ".join(parts[:MAX_FIELDS]) if parts else "all fields zero"
    return f"{spec['prefix']}: {body}.", unknown
